name: tickle
description: "가게부 앱"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.17
  go_router: ^14.8.0
  google_sign_in: ^6.2.2
  kakao_flutter_sdk: ^1.9.6
  provider: ^6.1.2
  sign_in_with_apple: ^6.1.4
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
